const emojiList = [
    { emoji: "😀", description: "grinning face" },
    { emoji: "😃", description: "smiling face with big eyes" },
    { emoji: "😄", description: "smiling face with smiling eyes" },
    { emoji: "😁", description: "beaming face with smiling eyes" },
    { emoji: "😆", description: "grinning squinting face" },
    { emoji: "😅", description: "grinning face with sweat" },
    { emoji: "🤣", description: "rolling on the floor laughing" },
    { emoji: "😂", description: "face with tears of joy" },
    { emoji: "🙂", description: "slightly smiling face" },
    { emoji: "🙃", description: "upside-down face" },
    { emoji: "🫠", description: "melting face" },
    { emoji: "😉", description: "winking face" },
    { emoji: "😊", description: "smiling face with smiling eyes" },
    { emoji: "😇", description: "smiling face with halo" },
    { emoji: "🥰", description: "smiling face with hearts" },
    { emoji: "😍", description: "smiling face with heart-eyes" },
    { emoji: "🤩", description: "star-struck" },
    { emoji: "😘", description: "face blowing a kiss" },
    { emoji: "😗", description: "kissing face" },
    { emoji: "☺️", description: "smiling face" },
    { emoji: "😚", description: "kissing face with closed eyes" },
    { emoji: "😙", description: "kissing face with smiling eyes" },
    { emoji: "🥲", description: "smiling face with tear" },
    { emoji: "😋", description: "face savoring food" },
    { emoji: "😛", description: "face with tongue" },
    { emoji: "😜", description: "winking face with tongue" },
    { emoji: "🤪", description: "zany face" },
    { emoji: "😝", description: "squinting face with tongue" },
    { emoji: "🤑", description: "money-mouth face" },
    { emoji: "🤗", description: "hugging face" },
    { emoji: "🤭", description: "face with hand over mouth" },
    { emoji: "🫢", description: "face with open eyes and hand over mouth" },
    { emoji: "🫣", description: "face with peeking eye" },
    { emoji: "🤫", description: "shushing face" },
    { emoji: "🤔", description: "thinking face" },
    { emoji: "🫡", description: "saluting face" },
    { emoji: "🤐", description: "zipper-mouth face" },
    { emoji: "🤨", description: "face with raised eyebrow" },
    { emoji: "😐", description: "neutral face" },
    { emoji: "😑", description: "expressionless face" },
    { emoji: "😶", description: "face without mouth" },
    { emoji: "🫥", description: "dotted line face" },
    { emoji: "😶‍🌫️", description: "face in clouds" },
    { emoji: "😏", description: "smirking face" },
    { emoji: "😒", description: "unamused face" },
    { emoji: "🙄", description: "face with rolling eyes" },
    { emoji: "😬", description: "grimacing face" },
    { emoji: "😮‍💨", description: "face exhaling" },
    { emoji: "🤥", description: "lying face" },
    { emoji: "🫨", description: "shaking face" },
    { emoji: "😌", description: "relieved face" },
    { emoji: "😔", description: "pensive face" },
    { emoji: "😪", description: "sleepy face" },
    { emoji: "🤤", description: "drooling face" },
    { emoji: "😴", description: "sleeping face" },
    { emoji: "😷", description: "face with medical mask" },
    { emoji: "🤒", description: "face with thermometer" },
    { emoji: "🤕", description: "face with head-bandage" },
    { emoji: "🤢", description: "nauseated face" },
    { emoji: "🤮", description: "face vomiting" },
    { emoji: "🤧", description: "sneezing face" },
    { emoji: "🥵", description: "hot face" },
    { emoji: "🥶", description: "cold face" },
    { emoji: "🥴", description: "woozy face" },
    { emoji: "😵", description: "face with crossed-out eyes" },
    { emoji: "🤯", description: "exploding head" },
    { emoji: "🤠", description: "cowboy hat face" },
    { emoji: "🥳", description: "partying face" },
    { emoji: "🥸", description: "disguised face" },
    { emoji: "😎", description: "smiling face with sunglasses" },
    { emoji: "🤓", description: "nerd face" },
    { emoji: "🧐", description: "face with monocle" },
    { emoji: "😕", description: "confused face" },
    { emoji: "🫤", description: "face with diagonal mouth" },
    { emoji: "😟", description: "worried face" },
    { emoji: "🙁", description: "slightly frowning face" },
    { emoji: "☹️", description: "frowning face" },
    { emoji: "😮", description: "face with open mouth" },
    { emoji: "😯", description: "hushed face" },
    { emoji: "😲", description: "astonished face" },
    { emoji: "😳", description: "flushed face" },
    { emoji: "🥺", description: "pleading face" },
    { emoji: "🥹", description: "face holding back tears" },
    { emoji: "😦", description: "frowning face with open mouth" },
    { emoji: "😧", description: "anguished face" },
    { emoji: "😨", description: "fearful face" },
    { emoji: "😰", description: "anxious face with sweat" },
    { emoji: "😥", description: "sad but relieved face" },
    { emoji: "😢", description: "crying face" },
    { emoji: "😭", description: "loudly crying face" }
  ];
  
  export default emojiList;
  